-- MySQL Script generated by MySQL Workbench
-- Fri Oct 16 15:43:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVENTO` (
  `idEvento` INT NOT NULL,
  `equipoLocal` VARCHAR(45) NOT NULL,
  `equipoVisitante` VARCHAR(45) NOT NULL,
  `fechaEvento` DATETIME NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `email` CHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APUESTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`APUESTA` (
  `idApuesta` INT NOT NULL,
  `tipo` DOUBLE NOT NULL,
  `cuota` DOUBLE NOT NULL,
  `dinero` DOUBLE NOT NULL,
  `fechaApuesta` DATETIME NOT NULL,
  `USUARIO_email` CHAR(45) NOT NULL,
  PRIMARY KEY (`idApuesta`, `USUARIO_email`),
  INDEX `fk_APUESTA_USUARIO1_idx` (`USUARIO_email` ASC) VISIBLE,
  CONSTRAINT `fk_APUESTA_USUARIO1`
    FOREIGN KEY (`USUARIO_email`)
    REFERENCES `mydb`.`USUARIO` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MERCADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MERCADO` (
  `idMercado` INT NOT NULL,
  `overUnder` VARCHAR(45) NOT NULL,
  `cuotaOver` DOUBLE NOT NULL,
  `cuotaUnder` DOUBLE NOT NULL,
  `dineroOver` DOUBLE NOT NULL,
  `dineroUnder` DOUBLE NOT NULL,
  `EVENTO_idEvento` INT NOT NULL,
  `APUESTA_idApuesta` INT NOT NULL,
  PRIMARY KEY (`idMercado`, `EVENTO_idEvento`, `APUESTA_idApuesta`),
  INDEX `fk_MERCADO_EVENTO_idx` (`EVENTO_idEvento` ASC) VISIBLE,
  INDEX `fk_MERCADO_APUESTA1_idx` (`APUESTA_idApuesta` ASC) VISIBLE,
  CONSTRAINT `fk_MERCADO_EVENTO`
    FOREIGN KEY (`EVENTO_idEvento`)
    REFERENCES `mydb`.`EVENTO` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MERCADO_APUESTA1`
    FOREIGN KEY (`APUESTA_idApuesta`)
    REFERENCES `mydb`.`APUESTA` (`idApuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUENTA` (
  `idCuenta` INT NOT NULL,
  `numTarjeta` INT NOT NULL,
  `saldo` DOUBLE NOT NULL,
  `nombreBanco` VARCHAR(45) NOT NULL,
  `USUARIO_email` CHAR(45) NOT NULL,
  PRIMARY KEY (`idCuenta`, `USUARIO_email`),
  INDEX `fk_CUENTA_USUARIO1_idx` (`USUARIO_email` ASC) VISIBLE,
  CONSTRAINT `fk_CUENTA_USUARIO1`
    FOREIGN KEY (`USUARIO_email`)
    REFERENCES `mydb`.`USUARIO` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
